// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfhVA4Td2dlFGWkHVDAmX6etbqx47_M3I',
    appId: '1:439411922472:web:82e89c5e255a86c5fd071d',
    messagingSenderId: '439411922472',
    projectId: 'final-project-61103',
    authDomain: 'final-project-61103.firebaseapp.com',
    storageBucket: 'final-project-61103.firebasestorage.app',
    measurementId: 'G-5VZEXTEQ00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDokXZ8YIJby1HXiPlZjEYVLRfYdpbzaAw',
    appId: '1:439411922472:android:4479bedad336ce1dfd071d',
    messagingSenderId: '439411922472',
    projectId: 'final-project-61103',
    storageBucket: 'final-project-61103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqnBaCz90mTmxK52F5YkoL_YHTPCoHt3A',
    appId: '1:439411922472:ios:6044923b58161dc7fd071d',
    messagingSenderId: '439411922472',
    projectId: 'final-project-61103',
    storageBucket: 'final-project-61103.firebasestorage.app',
    iosBundleId: 'com.example.sound2sign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqnBaCz90mTmxK52F5YkoL_YHTPCoHt3A',
    appId: '1:439411922472:ios:6044923b58161dc7fd071d',
    messagingSenderId: '439411922472',
    projectId: 'final-project-61103',
    storageBucket: 'final-project-61103.firebasestorage.app',
    iosBundleId: 'com.example.sound2sign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfhVA4Td2dlFGWkHVDAmX6etbqx47_M3I',
    appId: '1:439411922472:web:1c07680a6c6b37b0fd071d',
    messagingSenderId: '439411922472',
    projectId: 'final-project-61103',
    authDomain: 'final-project-61103.firebaseapp.com',
    storageBucket: 'final-project-61103.firebasestorage.app',
    measurementId: 'G-95Y7FW9ZSB',
  );
}
